# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a09cd24b93a2a9b6ab167b54947568d71fe4df0291c1fac42ece7c184e297611821a3531b570cc43b8128dbf35fbd363988ae102516baa5cfe4e1969741288d4

test:
  secret_key_base: b948a6e5ece8aff74b4aca2421160c145baee8e3401bb0273157b2ae50ebb13742808ef340e34838f8ad56b04e2bd6e6b5a482280a5c44e8dc51cc24577811b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
